import { describe, it, expect } from "vitest";
import {
  JUZ_STARTS,
  versesForJuz,
  pageForJuz,
  surahForPage,
  ayahCountForSurah,
  nextVerse,
  prevVerse,
  pageForVerse,
  lastVerseOfPage,
  PAGE_STARTS,
  TOTAL_JUZ,
  TOTAL_MUSHAF_PAGES,
} from "@/lib/navigation";
import surahIndex from "@/data/content/surah-index.json";

// Migrated from scripts/verify-memorization.mjs (the JUZ_STARTS + enumeration
// half), scripts/verify-navigation.mjs (the pageForJuz table), and
// scripts/verify-reading.mjs (the surahForPage monotonicity). These call the
// REAL navigation exports so a regression in the juz table, the enumeration
// walk, or the page->surah mapping fails the suite; the walk is never
// re-derived here (the whole point of the migration). The bundled surah index
// backs the gap check exactly as the source scripts did.

const index = surahIndex as Array<{ number: number; versesCount: number }>;
const TOTAL_VERSES = 6236;

// The standard Hafs 604-page Madinah mushaf juz start pages.
const STANDARD_JUZ = [
  1, 22, 42, 62, 82, 102, 121, 142, 162, 182,
  201, 222, 242, 262, 282, 302, 322, 342, 362, 382,
  402, 422, 442, 462, 482, 502, 522, 542, 562, 582,
];

describe("JUZ_STARTS table", () => {
  it("has exactly 30 entries", () => {
    expect(JUZ_STARTS.length).toBe(TOTAL_JUZ);
  });

  it("juz 1 starts at 1:1", () => {
    expect(JUZ_STARTS[0]).toEqual([1, 1]);
  });

  it("is strictly monotonic by surah then ayah", () => {
    for (let i = 1; i < JUZ_STARTS.length; i++) {
      const [s, a] = JUZ_STARTS[i];
      const [ps, pa] = JUZ_STARTS[i - 1];
      expect(s > ps || (s === ps && a > pa)).toBe(true);
    }
  });

  it("every juz start ayah is within its surah's real ayah count", () => {
    for (const [s, a] of JUZ_STARTS) {
      const count = ayahCountForSurah(s);
      expect(count).toBeGreaterThan(0);
      expect(a).toBeGreaterThanOrEqual(1);
      expect(a).toBeLessThanOrEqual(count);
    }
  });
});

describe("versesForJuz - full enumeration (6236 unique, 0 dupes, 0 gaps)", () => {
  const all: string[] = [];
  for (let j = 1; j <= TOTAL_JUZ; j++) all.push(...versesForJuz(j));
  const unique = new Set(all);

  it("produces exactly 6236 keys", () => {
    expect(all.length).toBe(TOTAL_VERSES);
  });

  it("has zero duplicates (6236 unique keys)", () => {
    expect(unique.size).toBe(all.length);
    expect(unique.size).toBe(TOTAL_VERSES);
  });

  it("has zero gaps against the bundled surah index", () => {
    let gaps = 0;
    for (const surah of index) {
      for (let a = 1; a <= surah.versesCount; a++) {
        if (!unique.has(`${surah.number}:${a}`)) gaps++;
      }
    }
    expect(gaps).toBe(0);
  });

  it("juz 30 ends at 114:6", () => {
    const last = versesForJuz(30);
    expect(last[last.length - 1]).toBe("114:6");
  });
});

describe("surahForPage - page->surah mapping", () => {
  it("page 1 resolves to Al-Fatihah (surah 1)", () => {
    expect(surahForPage(1)?.number).toBe(1);
  });

  it("page 604 resolves to a surah", () => {
    expect(surahForPage(TOTAL_MUSHAF_PAGES)).not.toBeNull();
  });

  it("is non-decreasing across all 604 pages", () => {
    let prev = 0;
    for (let p = 1; p <= TOTAL_MUSHAF_PAGES; p++) {
      const n = surahForPage(p)?.number ?? 0;
      expect(n).toBeGreaterThanOrEqual(prev);
      prev = n;
    }
  });
});

describe("pageForJuz - standard mushaf start pages", () => {
  it("matches the standard 30-page juz table", () => {
    for (let juz = 1; juz <= TOTAL_JUZ; juz++) {
      expect(pageForJuz(juz)).toBe(STANDARD_JUZ[juz - 1]);
    }
  });
});

// The offline page->verse table (src/lib/page-starts.ts, generated by
// scripts/fetch-page-starts.mjs). Guarded here the same way JUZ_STARTS is: the
// real export is enumerated, never re-derived, so a drifted capture fails the
// suite.
describe("PAGE_STARTS table", () => {
  it("has exactly 604 entries", () => {
    expect(PAGE_STARTS.length).toBe(TOTAL_MUSHAF_PAGES);
  });

  it("page 1 starts at 1:1", () => {
    expect(PAGE_STARTS[0]).toEqual([1, 1]);
  });

  it("is strictly monotonic by surah then ayah", () => {
    for (let i = 1; i < PAGE_STARTS.length; i++) {
      const [s, a] = PAGE_STARTS[i];
      const [ps, pa] = PAGE_STARTS[i - 1];
      expect(s > ps || (s === ps && a > pa)).toBe(true);
    }
  });

  it("every page start ayah is within its surah's real ayah count", () => {
    for (const [s, a] of PAGE_STARTS) {
      const count = ayahCountForSurah(s);
      expect(a).toBeGreaterThanOrEqual(1);
      expect(a).toBeLessThanOrEqual(count);
    }
  });

  it("walking page-by-page enumerates 6236 verses with 0 gaps, ending 114:6", () => {
    const all: string[] = [];
    for (let p = 1; p <= TOTAL_MUSHAF_PAGES; p++) {
      const [startS, startA] = PAGE_STARTS[p - 1];
      // Exclusive end = the first verse of the next page (sentinel past 114:6
      // for the final page), walked verse-by-verse honoring each surah's count.
      const [endS, endA] = p < TOTAL_MUSHAF_PAGES ? PAGE_STARTS[p] : [115, 1];
      let s = startS;
      let a = startA;
      while (s < endS || (s === endS && a < endA)) {
        all.push(`${s}:${a}`);
        a++;
        if (a > ayahCountForSurah(s)) {
          s++;
          a = 1;
        }
      }
    }
    const unique = new Set(all);
    expect(all.length).toBe(TOTAL_VERSES);
    expect(unique.size).toBe(TOTAL_VERSES);
    let gaps = 0;
    for (const surah of index) {
      for (let a = 1; a <= surah.versesCount; a++) {
        if (!unique.has(`${surah.number}:${a}`)) gaps++;
      }
    }
    expect(gaps).toBe(0);
    expect(all[all.length - 1]).toBe("114:6");
  });

  // Cross-check tying the two offline tables together. The first verse of every
  // juz falls ON its start page (JUZ_START_PAGES via pageForJuz) — true for all
  // 30. Note it is NOT always the FIRST verse of that page: the Quran.com /juzs
  // endpoint (source of JUZ_STARTS) and /verses/by_page endpoint (source of
  // PAGE_STARTS) diverge by a few verses at four seams (juz 4, 7, 11, 26), where
  // the page that begins a juz opens with the previous juz's tail. Both captures
  // are verified and unchanged; this asserts the relation that actually holds.
  it("aligns with JUZ_STARTS: each juz's first verse falls on its start page", () => {
    for (let j = 1; j <= TOTAL_JUZ; j++) {
      const [js, ja] = JUZ_STARTS[j - 1];
      expect(pageForVerse(js, ja)).toBe(pageForJuz(j));
    }
  });

  it("matches PAGE_STARTS at every juz seam except the four where the two API conventions diverge (juz 4, 7, 11, 26)", () => {
    const divergent = new Set([4, 7, 11, 26]);
    for (let j = 1; j <= TOTAL_JUZ; j++) {
      const pageStart = PAGE_STARTS[pageForJuz(j) - 1];
      const juzStart = JUZ_STARTS[j - 1];
      const equal = pageStart[0] === juzStart[0] && pageStart[1] === juzStart[1];
      expect(equal).toBe(!divergent.has(j));
    }
  });
});

describe("nextVerse / prevVerse - cross-surah seam math", () => {
  it("advances the ayah within a surah (2:5 -> 2:6)", () => {
    expect(nextVerse(2, 5)).toBe("2:6");
  });

  it("crosses a surah boundary at the last ayah (1:7 -> 2:1)", () => {
    expect(nextVerse(1, 7)).toBe("2:1");
  });

  it("crosses into At-Tawbah, which has no preceding bismillah (8:75 -> 9:1)", () => {
    expect(nextVerse(8, 75)).toBe("9:1");
  });

  it("returns null at 114:6 (the end of the Quran)", () => {
    expect(nextVerse(114, 6)).toBeNull();
  });

  it("rolls an over-count input to the next surah, never an out-of-range ayah (1:999 -> 2:1)", () => {
    expect(nextVerse(1, 999)).toBe("2:1");
  });

  it("steps back within a surah (2:6 -> 2:5)", () => {
    expect(prevVerse(2, 6)).toBe("2:5");
  });

  it("crosses a surah boundary backward to the previous surah's last ayah (2:1 -> 1:7)", () => {
    expect(prevVerse(2, 1)).toBe("1:7");
  });

  it("returns null at 1:1 (the start of the Quran)", () => {
    expect(prevVerse(1, 1)).toBeNull();
  });
});

describe("lastVerseOfPage", () => {
  it("page 1 ends at Al-Fatihah's last verse (1:7)", () => {
    expect(lastVerseOfPage(1)).toBe("1:7");
  });

  it("page 604 ends at 114:6", () => {
    expect(lastVerseOfPage(TOTAL_MUSHAF_PAGES)).toBe("114:6");
  });
});

describe("pageForVerse", () => {
  it("verse 1:1 is on page 1", () => {
    expect(pageForVerse(1, 1)).toBe(1);
  });

  it("is non-decreasing across a nextVerse walk of all 6236 verses, ending on page 604", () => {
    let prev = 0;
    let count = 0;
    let key: string | null = "1:1";
    while (key) {
      const [s, a] = key.split(":").map(Number);
      const page = pageForVerse(s, a);
      expect(page).toBeGreaterThanOrEqual(prev);
      prev = page;
      count++;
      key = nextVerse(s, a);
    }
    expect(count).toBe(TOTAL_VERSES);
    expect(prev).toBe(TOTAL_MUSHAF_PAGES);
  });
});
